language: python

python:
  - "3.6"

before_install:
  - sudo rm -f /etc/boto.cfg

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda create -q -n snakemake snakemake virtualenv python=$TRAVIS_PYTHON_VERSION
  - source activate snakemake
  - pip install ./
  - pip install --requirement test-requirements.txt codecov tox

script:
  - source activate snakemake
  - ./run-tests

# after_success:
#   - source activate snakemake
#   - codecov

notifications:
  email: false
