{% set name = "snakescale" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be810e60af9992794ff926b2d7e7502349ac61917c24d968588e3f8f4bb3cc04

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - snakemake >=4.5.1
  run:
    - python
    - snakemake >=4.5.1

about:
  home: https://github.com/clintval/snakescale
  license: MIT
  license_family: MIT
  license_file: 
  summary: Non-strict wrappers for the data pipelining language Snakemake.
  doc_url: http://snakescale.readthedocs.io/
  dev_url: 

extra:
  recipe-maintainers:
    - clintval
